export const SET_CURRENCIES = 'SET_CURRENCIES'
export const SET_TO = 'SET_TO'
export const SET_FROM = 'SET_FROM'
export const SET_MIN_AMOUNT = 'SET_MIN_AMOUNT'
export const SET_ESTIMATE_AMOUNT = 'SET_ESTIMATE_AMOUNT'
